# NN Assignment

Hassan Sherwani

# Combining Darasets

# 1)- Importing key modules

In [1]:
#support both Python 2 and Python 3 with minimal overhead.
from __future__ import absolute_import, division, print_function
#ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np 
import pandas as pd
import requests
import pickle

# 2) Loading and checking data

## 2.1)- Working with data-file1

### 1st data-file

In [3]:
df_1a = pd.read_csv('testset1A.csv',names=['m1','m2','m3','m4','m5','m6','m7','m8','m9','m10','m11','m12','m13','m14','m15','m16','m17','m18','m19','m20','m21','m22','m23','m24','m25'])
df_1a.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,0.572565,-0.014704,-0.352985,-0.012697,-0.138549,0.620313,-0.602656,-0.071517,-0.131941,-0.067118,...,-0.199931,-0.360027,0.154202,0.369976,0.320812,1.252255,1.154858,0.609724,-0.126952,0.075709
1,-1.271232,0.754440,-0.206883,-0.572400,-0.303629,1.783537,0.338053,0.684332,0.780279,0.981463,...,1.112403,-0.317894,0.062038,-0.539969,-0.475836,0.734146,-0.377487,-0.449741,0.386476,0.419884
2,-0.778364,-0.453716,-2.100201,-1.631793,0.106977,-0.589203,-0.879545,-0.592093,-1.009544,0.511542,...,1.595380,1.442629,1.253560,-0.355481,-1.208893,1.002466,0.186666,0.211632,-0.566621,-1.000671
3,0.123050,-0.028485,-2.110557,1.063871,-0.726543,0.830868,-0.573941,-0.114878,-0.202546,-0.922759,...,0.143878,0.924964,0.692511,0.194830,-0.937676,0.750807,-0.016080,-0.227677,0.806782,0.556675
4,-0.118888,-0.420055,-0.262475,0.652980,0.441975,-0.368197,-0.892770,-0.171982,0.698864,-0.022570,...,-0.430478,-0.092441,-0.098479,-0.818634,-0.410947,-0.682311,-1.804491,-0.457305,-0.861737,0.162936

In [4]:
df_1a.shape

(16000, 25)

### 2nd data-file

In [5]:
df_1b=pd.read_csv('testset1B.csv',names=['m1','m2','m3','m4','m5','m6','m7','m8','m9','m10','m11','m12','m13','m14','m15','m16','m17','m18','m19','m20','m21','m22','m23','m24','m25'])
df_1b.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,-2.576751,1.454457,-0.797617,-0.068095,0.427326,-0.766935,-1.430608,0.453900,-0.411322,-1.418911,...,-0.426212,-1.097138,-0.392415,-2.700466,-0.268030,0.339719,0.113876,-0.830255,-0.745786,0.120299
1,0.557821,-0.614547,-1.884439,-0.328170,-0.925417,-0.027375,-0.674162,0.524839,-0.366083,-0.052222,...,0.745734,0.907049,0.207623,0.738147,1.241511,-1.143762,0.717883,0.637519,0.123657,1.003731
2,0.189815,-0.028821,0.387855,0.505912,0.003976,-0.419956,2.518082,-1.702240,1.315501,-0.303887,...,-0.445056,-0.906442,-0.847724,0.615788,0.444622,-1.287194,-0.853554,1.434815,-1.345789,-0.368699
3,-0.190503,-0.590418,-0.112414,-1.549496,-0.809162,-0.497603,-1.371436,0.360082,0.087373,0.201154,...,-0.152522,-0.010447,1.422175,-0.586441,-0.815035,-1.993541,0.385756,-0.242427,-0.362867,-0.073414
4,-0.902186,0.164857,-0.848019,-0.429134,-1.421016,-0.027342,-0.277507,0.025876,-0.022579,-1.158496,...,-0.619502,0.426314,0.096023,-0.495887,0.583617,-0.194172,-0.471482,0.192652,-0.168350,-1.101099

In [6]:
df_1b.shape

(16000, 25)

### 3rd data-file

In [7]:
df_1c=pd.read_csv('testset1C.csv',names=['m1','m2','m3','m4','m5','m6','m7','m8','m9','m10','m11','m12','m13','m14','m15','m16','m17','m18','m19','m20','m21','m22','m23','m24','m25'])
df_1c.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,1.911620,1.780568,0.112782,0.023566,0.962295,1.555782,-0.115079,-1.822563,-0.940018,-1.250963,...,-0.291173,-0.051729,-1.016362,-1.157011,-0.087983,-0.143245,-1.322042,-0.128810,0.352823,-0.848771
1,-1.404434,-0.679314,0.824762,-1.832587,-0.498626,1.958490,-0.606151,-0.478504,0.340720,-0.720397,...,-0.846875,0.591674,-0.889451,1.057587,0.208140,-1.301169,0.154730,0.135555,0.597717,-0.560831
2,-0.043655,0.762334,1.167329,0.052801,-0.386838,0.155432,0.233975,2.347612,2.355708,0.344375,...,1.433116,0.287426,-0.266052,-0.890910,-0.443283,1.090979,-0.881858,0.469138,-0.723896,0.780626
3,1.219126,1.307099,0.663274,0.317437,2.365645,0.770653,1.792511,0.419561,1.827579,1.834503,...,1.165540,-0.551494,0.589346,2.112192,0.939042,-0.585487,1.093098,0.673904,-1.405872,0.495603
4,0.602711,2.037767,-0.406080,-1.168503,-1.523698,1.497330,-0.156217,-0.681928,-1.176521,-1.217670,...,0.611580,-0.299072,-0.804025,-0.845401,-0.442599,1.617233,0.046596,-0.027483,2.300126,-2.098665

In [8]:
df_1c.shape

(16000, 25)

### 4th data-file

In [9]:
df_1d=pd.read_csv('testset1D.csv',names=['m1','m2','m3','m4','m5','m6','m7','m8','m9','m10','m11','m12','m13','m14','m15','m16','m17','m18','m19','m20','m21','m22','m23','m24','m25'])
df_1d.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,1.312159,1.792499,1.344670,-0.486610,1.107547,-0.771320,0.016390,0.446286,-0.073729,-0.123637,...,0.515453,-1.200123,-0.077989,0.616607,1.112428,0.204814,0.805096,0.465794,-0.602995,1.538091
1,-1.033904,-0.367207,0.907344,0.554650,0.337684,-0.015096,0.097588,0.504592,-0.266477,-0.077006,...,-1.153989,-0.185934,0.571489,0.606080,-0.590793,-0.116663,-0.754702,-1.030098,-0.220970,1.714617
2,0.240373,0.051317,-0.873098,0.019531,-0.699226,-0.292993,0.222526,-0.374925,-1.048827,-1.008605,...,-0.153766,1.404317,0.664812,-1.094160,0.610560,-0.094158,1.341975,-0.631720,1.892594,-0.136623
3,0.655111,-1.722701,2.306501,1.568126,0.419238,-0.688739,0.296266,-0.107040,-0.211525,-0.093948,...,-0.592247,-0.627751,-0.401482,0.119997,-1.582148,0.784807,-0.453345,1.074648,0.580103,-0.948353
4,1.061321,0.743317,-1.222917,0.172989,-0.232392,-0.186593,-0.193252,-0.426116,0.782720,-0.844796,...,-0.085427,-0.530607,-0.470900,-0.058082,-0.117229,-0.648622,-2.234190,-1.634757,0.677809,0.626013

In [10]:
df_1d.shape

(16000, 25)

### 5th data-file

In [11]:
df_1e=pd.read_csv('testset1E.csv',names=['m1','m2','m3','m4','m5','m6','m7','m8','m9','m10','m11','m12','m13','m14','m15','m16','m17','m18','m19','m20','m21','m22','m23','m24','m25'])
df_1e.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,0.696859,0.497123,0.087743,0.257176,-0.285029,0.102449,-0.062597,0.539215,-0.489741,2.393081,...,-0.361114,0.020572,0.623679,-0.516947,0.610177,0.363177,-0.090002,0.531978,0.806115,0.138243
1,-0.229490,-1.410891,0.475261,0.055183,0.682398,0.795993,0.250034,-0.329281,0.124484,0.542105,...,-0.230190,0.574697,0.251126,0.904950,-0.109405,-0.369701,1.964010,1.300114,-0.003009,-0.661096
2,2.228071,1.042160,0.696894,-0.770098,-0.647393,-0.780329,1.151765,0.699445,-0.217503,-0.801720,...,-0.883257,1.441273,0.933471,-1.131043,-1.985277,-1.595090,-0.289037,0.593990,-0.530067,0.663122
3,0.300074,-0.248224,-1.985386,0.589129,-0.098360,0.791844,-0.867485,-0.161939,-1.651350,0.563893,...,-0.244475,-0.937310,0.435723,-0.150624,-0.988672,-1.643008,-1.121949,-0.072564,-0.323598,0.970885
4,-1.449043,0.026145,0.149044,-1.496834,0.920906,0.075570,0.760400,0.197384,-0.043909,-0.800026,...,1.563188,-1.209402,0.407075,-0.529562,0.844320,-0.134591,-0.196474,-0.404775,-1.767504,-0.513353

In [12]:
df_1e.shape

(16000, 25)

# Combining all five files 

- concate

df_row = pd.concat([df1, df2])

df_row

In [13]:
df_testset1=pd.concat([df_1a,df_1b,df_1c,df_1d,df_1e], ignore_index=True) # to adjust automatically row labels i.e index
df_testset1.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,0.572565,-0.014704,-0.352985,-0.012697,-0.138549,0.620313,-0.602656,-0.071517,-0.131941,-0.067118,...,-0.199931,-0.360027,0.154202,0.369976,0.320812,1.252255,1.154858,0.609724,-0.126952,0.075709
1,-1.271232,0.754440,-0.206883,-0.572400,-0.303629,1.783537,0.338053,0.684332,0.780279,0.981463,...,1.112403,-0.317894,0.062038,-0.539969,-0.475836,0.734146,-0.377487,-0.449741,0.386476,0.419884
2,-0.778364,-0.453716,-2.100201,-1.631793,0.106977,-0.589203,-0.879545,-0.592093,-1.009544,0.511542,...,1.595380,1.442629,1.253560,-0.355481,-1.208893,1.002466,0.186666,0.211632,-0.566621,-1.000671
3,0.123050,-0.028485,-2.110557,1.063871,-0.726543,0.830868,-0.573941,-0.114878,-0.202546,-0.922759,...,0.143878,0.924964,0.692511,0.194830,-0.937676,0.750807,-0.016080,-0.227677,0.806782,0.556675
4,-0.118888,-0.420055,-0.262475,0.652980,0.441975,-0.368197,-0.892770,-0.171982,0.698864,-0.022570,...,-0.430478,-0.092441,-0.098479,-0.818634,-0.410947,-0.682311,-1.804491,-0.457305,-0.861737,0.162936

In [14]:
df_testset1.shape

(80000, 25)

Perfect!

First data-set has combined. We will do with other 2 datasets and name them as df_testset2 & df_testset3

### Save testset1 as pickle and csv

In [15]:
df_testset1.to_pickle('testset1.pkl')
pickle.dump(df_testset1, open("df_testset1.pkl", "wb"))

In [16]:
df_testset1.to_csv('testset1.csv', index = False)

## 2.2)- Working with data-file2

### 1st file

In [17]:
df_2a = pd.read_csv('testset2A.csv',names=['m1','m2','m3','m4','m5','m6','m7','m8','m9','m10','m11','m12','m13','m14','m15','m16','m17','m18','m19','m20','m21','m22','m23','m24','m25'])
df_2a.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,0.572565,-0.014704,-0.352985,-0.012697,-0.138549,0.620313,-0.602656,-0.071517,-0.131941,-0.067118,...,-0.199931,-0.360027,0.154202,0.369976,0.320812,1.252255,1.154858,0.609724,-0.126952,0.075709
1,-1.233754,0.643106,-0.268247,-0.588117,-0.231391,1.816856,0.369814,0.784052,0.870746,1.033480,...,0.943058,-0.475841,-0.085267,-0.601490,-0.601191,0.635048,-0.433662,-0.456993,0.429443,0.423808
2,-0.778364,-0.453716,-2.100201,-1.631793,0.106977,-0.589203,-0.879545,-0.592093,-1.009544,0.511542,...,1.595380,1.442629,1.253560,-0.355481,-1.208893,1.002466,0.186666,0.211632,-0.566621,-1.000671
3,0.215642,0.012791,-2.107229,0.991472,-0.796206,0.750239,-0.520066,-0.161497,-0.197805,-0.985420,...,0.099799,0.937634,0.778357,0.363507,-0.775966,0.837327,0.046322,-0.209766,0.858010,0.596164
4,-0.118888,-0.420055,-0.262475,0.652980,0.441975,-0.368197,-0.892770,-0.171982,0.698864,-0.022570,...,-0.430478,-0.092441,-0.098479,-0.818634,-0.410947,-0.682311,-1.804491,-0.457305,-0.861737,0.162936

In [18]:
df_2a.shape

(16000, 25)

### 2nd file

In [19]:
df_2b = pd.read_csv('testset2B.csv',names=['m1','m2','m3','m4','m5','m6','m7','m8','m9','m10','m11','m12','m13','m14','m15','m16','m17','m18','m19','m20','m21','m22','m23','m24','m25'])
df_2b.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,-2.576751,1.454457,-0.797617,-0.068095,0.427326,-0.766935,-1.430608,0.453900,-0.411322,-1.418911,...,-0.426212,-1.097138,-0.392415,-2.700466,-0.268030,0.339719,0.113876,-0.830255,-0.745786,0.120299
1,0.707379,-0.477314,-1.809228,-0.307909,-0.956505,-0.085985,-0.614002,0.578451,-0.281709,0.025846,...,0.729583,0.964268,0.224505,0.803105,1.269940,-1.118374,0.688186,0.578953,0.003214,1.002085
2,0.189815,-0.028821,0.387855,0.505912,0.003976,-0.419956,2.518082,-1.702240,1.315501,-0.303887,...,-0.445056,-0.906442,-0.847724,0.615788,0.444622,-1.287194,-0.853554,1.434815,-1.345789,-0.368699
3,-0.183441,-0.547892,-0.115129,-1.453954,-0.747335,-0.439347,-1.315475,0.448621,0.191662,0.347590,...,-0.080553,0.154121,1.556903,-0.465766,-0.739266,-1.935430,0.302296,-0.286869,-0.395326,0.020476
4,-0.902186,0.164857,-0.848019,-0.429134,-1.421016,-0.027342,-0.277507,0.025876,-0.022579,-1.158496,...,-0.619502,0.426314,0.096023,-0.495887,0.583617,-0.194172,-0.471482,0.192652,-0.168350,-1.101099

In [20]:
df_2b.shape

(16000, 25)

### 3rd file

In [21]:
df_2c = pd.read_csv('testset2C.csv',names=['m1','m2','m3','m4','m5','m6','m7','m8','m9','m10','m11','m12','m13','m14','m15','m16','m17','m18','m19','m20','m21','m22','m23','m24','m25'])
df_2c.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,1.911620,1.780568,0.112782,0.023566,0.962295,1.555782,-0.115079,-1.822563,-0.940018,-1.250963,...,-0.291173,-0.051729,-1.016362,-1.157011,-0.087983,-0.143245,-1.322042,-0.128810,0.352823,-0.848771
1,-1.304072,-0.544609,0.925561,-1.674099,-0.344540,2.123700,-0.435636,-0.223616,0.550764,-0.627671,...,-0.811771,0.489979,-1.038580,0.956280,0.160888,-1.387246,0.095923,0.001805,0.485947,-0.547305
2,-0.043655,0.762334,1.167329,0.052801,-0.386838,0.155432,0.233975,2.347612,2.355708,0.344375,...,1.433116,0.287426,-0.266052,-0.890910,-0.443283,1.090979,-0.881858,0.469138,-0.723896,0.780626
3,1.136347,1.269873,0.586367,0.279873,2.265754,0.680048,1.713126,0.369021,1.698507,1.716161,...,0.818867,-0.957298,0.238203,1.780986,0.654160,-0.792321,0.896427,0.447563,-1.620678,0.315687
4,0.602711,2.037767,-0.406080,-1.168503,-1.523698,1.497330,-0.156217,-0.681928,-1.176521,-1.217670,...,0.611580,-0.299072,-0.804025,-0.845401,-0.442599,1.617233,0.046596,-0.027483,2.300126,-2.098665

In [22]:
df_2c.shape

(16000, 25)

### 4th file

In [23]:
df_2d = pd.read_csv('testset2D.csv',names=['m1','m2','m3','m4','m5','m6','m7','m8','m9','m10','m11','m12','m13','m14','m15','m16','m17','m18','m19','m20','m21','m22','m23','m24','m25'])
df_2d.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,1.312159,1.792499,1.344670,-0.486610,1.107547,-0.771320,0.016390,0.446286,-0.073729,-0.123637,...,0.515453,-1.200123,-0.077989,0.616607,1.112428,0.204814,0.805096,0.465794,-0.602995,1.538091
1,-1.006047,-0.305085,0.965417,0.578122,0.459089,0.117034,0.202086,0.559514,-0.258344,-0.093678,...,-1.199421,-0.220136,0.550204,0.599638,-0.508037,-0.018907,-0.694131,-1.024665,-0.241417,1.699998
2,0.240373,0.051317,-0.873098,0.019531,-0.699226,-0.292993,0.222526,-0.374925,-1.048827,-1.008605,...,-0.153766,1.404317,0.664812,-1.094160,0.610560,-0.094158,1.341975,-0.631720,1.892594,-0.136623
3,0.704747,-1.681349,2.305027,1.697906,0.534531,-0.475969,0.338222,-0.156461,-0.307495,-0.170311,...,-0.560771,-0.597030,-0.445837,-0.021948,-1.687892,0.658664,-0.544479,0.963719,0.585417,-0.945237
4,1.061321,0.743317,-1.222917,0.172989,-0.232392,-0.186593,-0.193252,-0.426116,0.782720,-0.844796,...,-0.085427,-0.530607,-0.470900,-0.058082,-0.117229,-0.648622,-2.234190,-1.634757,0.677809,0.626013

In [24]:
df_2d.shape

(16000, 25)

### 5th file

In [25]:
df_2e = pd.read_csv('testset2E.csv',names=['m1','m2','m3','m4','m5','m6','m7','m8','m9','m10','m11','m12','m13','m14','m15','m16','m17','m18','m19','m20','m21','m22','m23','m24','m25'])
df_2e.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,0.696859,0.497123,0.087743,0.257176,-0.285029,0.102449,-0.062597,0.539215,-0.489741,2.393081,...,-0.361114,0.020572,0.623679,-0.516947,0.610177,0.363177,-0.090002,0.531978,0.806115,0.138243
1,-0.348561,-1.500973,0.393409,0.034075,0.682869,0.938827,0.451886,-0.130998,0.249677,0.606364,...,-0.324788,0.513823,0.334232,0.987005,0.029486,-0.265125,2.048247,1.404577,0.132801,-0.525937
2,2.228071,1.042160,0.696894,-0.770098,-0.647393,-0.780329,1.151765,0.699445,-0.217503,-0.801720,...,-0.883257,1.441273,0.933471,-1.131043,-1.985277,-1.595090,-0.289037,0.593990,-0.530067,0.663122
3,0.377492,-0.160187,-1.880376,0.567728,-0.096652,0.747307,-0.765961,-0.102815,-1.573876,0.551001,...,-0.216159,-0.867195,0.518368,0.075184,-0.766737,-1.391406,-0.980858,0.056221,-0.168893,1.139558
4,-1.449043,0.026145,0.149044,-1.496834,0.920906,0.075570,0.760400,0.197384,-0.043909,-0.800026,...,1.563188,-1.209402,0.407075,-0.529562,0.844320,-0.134591,-0.196474,-0.404775,-1.767504,-0.513353

In [26]:
df_2e.shape

(16000, 25)

### Combining all five files in testset2

In [27]:
df_testset2=pd.concat([df_2a,df_2b,df_2c,df_2d,df_2e], ignore_index=True) 
df_testset2.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,0.572565,-0.014704,-0.352985,-0.012697,-0.138549,0.620313,-0.602656,-0.071517,-0.131941,-0.067118,...,-0.199931,-0.360027,0.154202,0.369976,0.320812,1.252255,1.154858,0.609724,-0.126952,0.075709
1,-1.233754,0.643106,-0.268247,-0.588117,-0.231391,1.816856,0.369814,0.784052,0.870746,1.033480,...,0.943058,-0.475841,-0.085267,-0.601490,-0.601191,0.635048,-0.433662,-0.456993,0.429443,0.423808
2,-0.778364,-0.453716,-2.100201,-1.631793,0.106977,-0.589203,-0.879545,-0.592093,-1.009544,0.511542,...,1.595380,1.442629,1.253560,-0.355481,-1.208893,1.002466,0.186666,0.211632,-0.566621,-1.000671
3,0.215642,0.012791,-2.107229,0.991472,-0.796206,0.750239,-0.520066,-0.161497,-0.197805,-0.985420,...,0.099799,0.937634,0.778357,0.363507,-0.775966,0.837327,0.046322,-0.209766,0.858010,0.596164
4,-0.118888,-0.420055,-0.262475,0.652980,0.441975,-0.368197,-0.892770,-0.171982,0.698864,-0.022570,...,-0.430478,-0.092441,-0.098479,-0.818634,-0.410947,-0.682311,-1.804491,-0.457305,-0.861737,0.162936

In [28]:
df_testset2.shape

(80000, 25)

### Save work

In [29]:
df_testset2.to_pickle('testset2.pkl')
df_testset2.to_csv('testset2.csv')

## 2.3)- Working with data-file3

### 1st file

In [30]:
df_3a = pd.read_csv('testset3A.csv',names=['m1','m2','m3','m4','m5','m6','m7','m8','m9','m10','m11','m12','m13','m14','m15','m16','m17','m18','m19','m20','m21','m22','m23','m24','m25'])
df_3a.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,0.111771,-0.019099,-0.076978,0.000673,-0.015912,0.123728,-0.126245,0.004603,-0.011020,-0.000368,...,-0.140342,-0.129376,-0.006367,0.033683,0.011117,0.161306,0.094439,-0.026443,-0.144413,-0.071164
1,-0.184091,0.216673,-0.014954,-0.069772,0.005479,0.353513,-0.011455,0.051448,0.042422,0.067612,...,0.211127,-0.099469,-0.006718,-0.096733,-0.051730,0.172214,-0.066792,-0.051919,0.110749,0.077489
2,0.008035,0.062072,-0.241956,-0.069209,0.258024,0.052788,-0.017690,0.040586,-0.034276,0.238631,...,0.119980,0.052255,0.003164,-0.274543,-0.357405,0.108541,-0.067585,-0.043078,-0.155833,-0.170760
3,-0.036022,-0.050153,-0.385066,0.277908,-0.117614,0.184526,-0.111192,-0.003463,-0.014552,-0.132177,...,0.120375,0.215093,0.102839,-0.008383,-0.198529,0.144325,-0.030426,-0.061379,0.129043,0.048179
4,-0.001896,-0.049135,-0.007538,0.146521,0.059264,-0.088644,-0.151540,0.014254,0.154770,-0.019627,...,0.061813,0.101509,0.068615,-0.075030,0.017009,-0.032692,-0.202226,0.102084,-0.000502,0.166624

In [31]:
df_3a.shape

(16000, 25)

### 2nd file

In [32]:
df_3b = pd.read_csv('testset3B.csv',names=['m1','m2','m3','m4','m5','m6','m7','m8','m9','m10','m11','m12','m13','m14','m15','m16','m17','m18','m19','m20','m21','m22','m23','m24','m25'])
df_3b.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,-0.413557,0.407792,-0.113144,0.044565,0.113548,-0.118177,-0.194830,0.191551,-0.017527,-0.185464,...,-0.092145,-0.175505,0.003747,-0.383944,0.164513,0.207370,0.094997,-0.099931,-0.051670,0.112603
1,0.105322,-0.130143,-0.297591,0.062479,-0.057336,0.112054,-0.030498,0.181313,-0.034797,0.029069,...,0.143046,0.122571,-0.036646,0.060542,0.121385,-0.310754,0.086933,0.045103,-0.056618,0.114695
2,-0.031629,-0.073918,0.015722,0.025386,-0.067832,-0.120876,0.400747,-0.424152,0.204341,-0.128278,...,-0.006191,-0.076468,-0.036514,0.222129,0.129160,-0.208988,-0.059497,0.344231,-0.242410,-0.005143
3,0.090078,-0.001058,0.080233,-0.186835,0.006550,0.057477,-0.105494,0.224472,0.093100,0.083516,...,-0.015378,0.006101,0.239230,-0.171127,-0.166356,-0.307781,0.201623,0.026894,-0.004243,0.051603
4,-0.121767,0.096862,-0.105842,0.001553,-0.161451,0.129177,0.039803,0.076930,0.042804,-0.159946,...,0.079681,0.225729,0.085193,-0.040787,0.152838,-0.025608,-0.063515,0.062853,-0.019679,-0.175984

In [33]:
df_3b.shape

(16000, 25)

### 3rd file

In [34]:
df_3c = pd.read_csv('testset3C.csv',names=['m1','m2','m3','m4','m5','m6','m7','m8','m9','m10','m11','m12','m13','m14','m15','m16','m17','m18','m19','m20','m21','m22','m23','m24','m25'])
df_3c.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,0.284884,0.177614,-0.162370,-0.137696,0.056381,0.141415,-0.172908,-0.407619,-0.135026,-0.140823,...,0.102967,0.107398,-0.085101,-0.067322,0.139566,0.073742,-0.150733,0.098866,0.147687,-0.097877
1,-0.160735,0.025790,0.264369,-0.263715,0.046911,0.440319,-0.131321,-0.071100,0.077757,-0.126394,...,-0.199563,0.093068,-0.186618,0.208230,-0.004212,-0.257860,0.071693,0.041289,0.110636,-0.112816
2,-0.114453,0.055143,0.109882,-0.108658,-0.158309,-0.020838,0.004734,0.354079,0.253890,-0.149742,...,0.256628,-0.018012,-0.108411,-0.178895,-0.042782,0.240532,-0.158084,0.121828,-0.121320,0.175340
3,0.154960,0.132618,-0.020240,-0.079346,0.280226,-0.062040,0.123566,-0.142349,0.130016,0.093354,...,0.047073,-0.255272,0.018024,0.267529,-0.001108,-0.257419,0.102686,0.007906,-0.336945,0.092562
4,0.191703,0.369458,-0.149894,-0.232284,-0.220267,0.366582,-0.036918,-0.112179,-0.159290,-0.105137,...,0.200280,-0.023506,-0.106436,-0.068944,0.024051,0.358252,-0.024777,-0.036356,0.352681,-0.478051

In [35]:
df_3c.shape

(16000, 25)

### 4th file

In [36]:
df_3d = pd.read_csv('testset3D.csv',names=['m1','m2','m3','m4','m5','m6','m7','m8','m9','m10','m11','m12','m13','m14','m15','m16','m17','m18','m19','m20','m21','m22','m23','m24','m25'])
df_3d.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,0.192494,0.212143,0.082435,-0.245403,0.085360,-0.255004,-0.053169,0.034574,-0.055669,-0.049313,...,0.045885,-0.257865,0.017339,0.124269,0.165963,-0.035783,0.072787,-0.008111,-0.182838,0.227737
1,-0.203198,-0.019509,0.201334,0.076512,0.019778,-0.050048,-0.013779,0.053308,-0.098896,-0.039826,...,-0.174910,0.051139,0.162867,0.114389,-0.121229,-0.001168,-0.107873,-0.116789,0.057343,0.363810
2,0.082162,0.019483,-0.139811,0.046562,-0.092980,0.000089,0.091446,-0.035845,-0.131245,-0.081379,...,-0.109813,0.179686,-0.000302,-0.297998,0.072147,-0.070444,0.184224,-0.206649,0.275229,-0.147314
3,0.168723,-0.275455,0.493841,0.207168,-0.049123,-0.226825,-0.004778,-0.072811,-0.070679,-0.028654,...,-0.222567,-0.159420,-0.070448,0.036713,-0.257497,0.228401,-0.058068,0.216667,0.062297,-0.209745
4,0.172592,0.071512,-0.275992,0.037737,-0.042513,-0.024158,-0.026457,-0.063709,0.165281,-0.158574,...,-0.012936,-0.082038,-0.045638,0.038899,0.016126,-0.078941,-0.311375,-0.096222,0.335931,0.195661

In [37]:
df_3d.shape

(16000, 25)

### 5th file

In [39]:
df_3e = pd.read_csv('testset3E.csv',names=['m1','m2','m3','m4','m5','m6','m7','m8','m9','m10','m11','m12','m13','m14','m15','m16','m17','m18','m19','m20','m21','m22','m23','m24','m25'])
df_3e.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,0.007980,-0.031252,-0.089689,-0.038523,-0.114111,-0.016815,-0.034247,0.087175,-0.104628,0.407658,...,-0.107628,-0.009605,0.092330,-0.127480,0.100447,0.028885,-0.059115,0.073749,0.094639,-0.040762
1,0.047574,-0.160884,0.219847,0.071045,0.152764,0.128180,0.005620,-0.097081,0.001290,0.067001,...,0.012483,0.143980,0.045928,0.143943,-0.068855,-0.094245,0.324247,0.118439,-0.135609,-0.216049
2,0.470803,0.120077,0.025509,-0.239706,-0.147085,-0.122669,0.237356,0.082320,-0.094008,-0.159793,...,-0.162597,0.274938,0.098717,-0.280262,-0.332429,-0.144922,0.133147,0.228311,-0.042043,0.180082
3,0.069178,-0.049964,-0.326621,0.209912,0.027677,0.159073,-0.165901,0.007057,-0.240255,0.215479,...,0.159002,-0.011033,0.225758,0.053771,-0.106219,-0.177537,-0.030146,0.163696,0.061350,0.247505
4,-0.262463,0.076958,0.082904,-0.220730,0.257116,0.030732,0.135447,-0.005886,-0.049483,-0.164506,...,0.294165,-0.268641,0.089034,-0.095691,0.168590,-0.048017,-0.043986,-0.068569,-0.272999,0.032841

In [40]:
df_3e.shape

(16000, 25)

### Combine all testset3 files

In [41]:
df_testset3=pd.concat([df_3a,df_3b,df_3c,df_3d,df_3e], ignore_index=True) 
df_testset3.head()

,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,...,m16,m17,m18,m19,m20,m21,m22,m23,m24,m25
0,0.111771,-0.019099,-0.076978,0.000673,-0.015912,0.123728,-0.126245,0.004603,-0.011020,-0.000368,...,-0.140342,-0.129376,-0.006367,0.033683,0.011117,0.161306,0.094439,-0.026443,-0.144413,-0.071164
1,-0.184091,0.216673,-0.014954,-0.069772,0.005479,0.353513,-0.011455,0.051448,0.042422,0.067612,...,0.211127,-0.099469,-0.006718,-0.096733,-0.051730,0.172214,-0.066792,-0.051919,0.110749,0.077489
2,0.008035,0.062072,-0.241956,-0.069209,0.258024,0.052788,-0.017690,0.040586,-0.034276,0.238631,...,0.119980,0.052255,0.003164,-0.274543,-0.357405,0.108541,-0.067585,-0.043078,-0.155833,-0.170760
3,-0.036022,-0.050153,-0.385066,0.277908,-0.117614,0.184526,-0.111192,-0.003463,-0.014552,-0.132177,...,0.120375,0.215093,0.102839,-0.008383,-0.198529,0.144325,-0.030426,-0.061379,0.129043,0.048179
4,-0.001896,-0.049135,-0.007538,0.146521,0.059264,-0.088644,-0.151540,0.014254,0.154770,-0.019627,...,0.061813,0.101509,0.068615,-0.075030,0.017009,-0.032692,-0.202226,0.102084,-0.000502,0.166624

In [42]:
df_testset3.shape

(80000, 25)

### Save work

In [43]:
df_testset3.to_pickle('testset3.pkl')
df_testset3.to_csv('testset3.csv')